### ISSUE TITLE
Reverse Proxy setup results in infinite socket.io error loop

### ISSUE THREAD

**Issue by ngInit** [Rachnus/GIMP-Tracker#19]
Hey - I was able to get the app running locally with an npm http-server. Got it connected to my backend using the reverse proxy URL no problem. Backend reverse proxy URL works for the Plugin connection as well.

The problem comes in with using a reverse proxy to access the frontend. I'm getting an infinite socket.io loop.

There's possibly some setting in the [SWAG](https://docs.linuxserver.io/images/docker-swag) proxy-confs file that could fix it... But IDK - I have a lot of different working configs and after browsing through them, comparing, and testing a few things... I'm out of ideas.

You can see the error [here](https://osrs.bognet.xyz/)

**Comment by AntonyGarand** [comment]
Looks like you're not properly setting the reverse-proxy for the /socket.io path, it's returning a 404 instead of the proper connection.
This is the first step socket.io uses to connect, before upgrading to a real websocket connection.

![image](https://user-images.githubusercontent.com/9059487/140087246-ec35f883-4065-4712-a5af-187e729c4601.png)

**Comment by ngInit** [comment]
Well yeah, any ideas on what to fix on the config for that though? Up until now I haven't had any other containers with a 404 issue on the default `/` location, so I have no clue. This is what I have right now:

osrs-gt-frontend.subdomain.conf
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name osrs.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_port 5000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

and I've been trying to add this block of code with no luck, inside and outside of the server { } block because apparently that can make a difference between subdomains and subfolders and I'm not sure which one I need to do to fix this, or if this is even the correct location

```
location ^~ /socket.io/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_port 5000;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

**Comment by AntonyGarand** [comment]
What I did for `map.osrs.cloud` is to use a different subdomain for the api: `map-api.osrs.cloud`
It's not as clean, but it does the job well

Otherwise as it's not an issue with the project itself but a reverse proxy issue, I can't really help you with that

**Comment by ngInit** [comment]
And by API, you mean the backend? LOL - well I think that comment may have done it.

I had my backend setup on a different URL too, but apparently that was actually the cause of my issue. I changed the port on the /socket-io/ path to point to the backend instead and that fixed it.

Here's an example config for anyone else setting this up through SWAG
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name osrs.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app osrs;
        set $upstream_port 5000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location ^~ /socket.io/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app osrs;
        set $upstream_port 5001;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```
